---
title: "lasso"
author: "Ciara Duggan"
date: "12/1/2020"
output: pdf_document
---

This markdown file contains all of the data cleaning and analysis behind my
LASSO model.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Setting up file and loading libraries

library(tidyverse)
library(readr)
library(rstanarm)
library(janitor)
library(tidymodels)
library(stats)
library(glmnet)
library(doParallel)
library(vip)
```


```{r read_csv, cache=TRUE}

# Reading in csv and setting column specifications

wb_wellness_raw <-  read_csv(file = "data/raw_data/WORLD_BANK.csv", 
                         skip = 1,
                         col_types = cols(
                           StartDate = col_character(),
                           EndDate = col_character(),
                           Status = col_double(),
                           IPAddress = col_character(),
                           Progress = col_double(),
                           `Duration (in seconds)` = col_double(),
                           Finished = col_double(),
                           RecordedDate = col_character(),
                           ResponseId = col_character(),
                           LocationLatitude = col_double(),
                           LocationLongitude = col_double(),
                           DistributionChannel = col_character(),
                           UserLanguage = col_character(),
                           Q166 = col_double(),
                           Q175 = col_double(),
                           Q112_NPS_GROUP = col_double(),
                           Q112 = col_double(),
                           Q112_NPS_GROUP_1 = col_double(),
                           Q112_1 = col_double(),
                           Q113_NPS_GROUP = col_double(),
                           Q113 = col_double(),
                           `7_NPS_GROUP` = col_double(),
                           `7` = col_double(),
                           `9_NPS_GROUP` = col_double(),
                           `9` = col_double(),
                           Q114_NPS_GROUP = col_double(),
                           Q114 = col_double(),
                           Q111_NPS_GROUP = col_double(),
                           Q111 = col_double(),
                           `20_NPS_GROUP` = col_double(),
                           `20` = col_double(),
                           Q111_NPS_GROUP_1 = col_double(),
                           Q111_1 = col_double(),
                           `21_NPS_GROUP` = col_double(),
                           `21` = col_double(),
                           `22_NPS_GROUP` = col_double(),
                           `22` = col_double(),
                           Q115_NPS_GROUP = col_double(),
                           Q115 = col_double(),
                           `24_NPS_GROUP` = col_double(),
                           `24` = col_double(),
                           `25_NPS_GROUP` = col_double(),
                           `25` = col_double(),
                           Q117_NPS_GROUP = col_double(),
                           Q117 = col_double(),
                           Q118_NPS_GROUP = col_double(),
                           Q118 = col_double(),
                           Q119_NPS_GROUP = col_double(),
                           Q119 = col_double(),
                           `5_NPS_GROUP` = col_double(),
                           `5` = col_double(),
                           Q121_NPS_GROUP = col_double(),
                           Q121 = col_double(),
                           Q122_NPS_GROUP = col_double(),
                           Q122 = col_double(),
                           Q116_NPS_GROUP = col_double(),
                           Q116 = col_double(),
                           `26_NPS_GROUP` = col_double(),
                           `26` = col_double(),
                           `27_NPS_GROUP` = col_double(),
                           `27` = col_double(),
                           Q120_NPS_GROUP = col_double(),
                           Q120 = col_double(),
                           Q93_1 = col_double(),
                           Q93_2 = col_double(),
                           Q93_3 = col_double(),
                           Q93_4 = col_double(),
                           Q93_5 = col_double(),
                           Q93_6 = col_double(),
                           Q134 = col_double(),
                           Q157 = col_double(),
                           Q190 = col_double(),
                           Q135 = col_double(),
                           Q136 = col_double(),
                           Q137 = col_double(),
                           Q158 = col_double(),
                           Q161 = col_double(),
                           Q159 = col_double(),
                           Q140 = col_double(),
                           Q194 = col_double(),
                           Q149 = col_double(),
                           `44_1` = col_double(),
                           `44_2` = col_double(),
                           `44_3` = col_double(),
                           `44_4` = col_double(),
                           `44_5` = col_double(),
                           `44_6` = col_double(),
                           `44_7` = col_double(),
                           `44_8` = col_double(),
                           `44_9` = col_double(),
                           `44_10` = col_double(),
                           `45_1` = col_double(),
                           `45_2` = col_double(),
                           `45_3` = col_double(),
                           `45_4` = col_double(),
                           `45_5` = col_double(),
                           `45_6` = col_double(),
                           `45_7` = col_double(),
                           `45_8` = col_double(),
                           `45_9` = col_double(),
                           `45_10` = col_double(),
                           `46_1` = col_double(),
                           `46_2` = col_double(),
                           `46_3` = col_double(),
                           `46_4` = col_double(),
                           `46_5` = col_double(),
                           `46_6` = col_double(),
                           `46_7` = col_double(),
                           `46_8` = col_double(),
                           `46_9` = col_double(),
                           `48_1` = col_double(),
                           `48_2` = col_double(),
                           `48_3` = col_double(),
                           `48_4` = col_double(),
                           `48_5` = col_double(),
                           `48_6` = col_double(),
                           `48_7` = col_double(),
                           `48_8` = col_double(),
                           `48_9` = col_double(),
                           `48_10` = col_double(),
                           `48_11` = col_double(),
                           `48_12` = col_double(),
                           `40_1` = col_double(),
                           `40_2` = col_double(),
                           `40_3` = col_double(),
                           `40_4` = col_double(),
                           `40_5` = col_double(),
                           `40_6` = col_double(),
                           `40_7` = col_double(),
                           `40_8` = col_double(),
                           `40_9` = col_double(),
                           `40_10` = col_double(),
                           `40_11` = col_double(),
                           `40_12` = col_double(),
                           `43_NPS_GROUP` = col_double(),
                           `43` = col_double(),
                           `12` = col_double(),
                           `41` = col_double(),
                           `52` = col_double(),
                           `49_NPS_GROUP` = col_double(),
                           `49` = col_double(),
                           `47_1` = col_double(),
                           `47_2` = col_double(),
                           `47_3` = col_double(),
                           `47_4` = col_double(),
                           `47_5` = col_double(),
                           `47_6` = col_double(),
                           `47_7` = col_double(),
                           `47_8` = col_double(),
                           `47_9` = col_double(),
                           `47_10` = col_double(),
                           `47_11` = col_double(),
                           `47_12` = col_double(),
                           `6` = col_double(),
                           `16` = col_double(),
                           `13` = col_double(),
                           `10` = col_double(),
                           `8` = col_double(),
                           `14` = col_double(),
                           `11` = col_double(),
                           `17` = col_double(),
                           `15` = col_double(),
                           Q146_1 = col_double(),
                           Q146_2 = col_double(),
                           Q146_3 = col_double(),
                           Q146_4 = col_double(),
                           Q146_5 = col_double(),
                           Q146_6 = col_double(),
                           Q146_7 = col_double(),
                           Q146_8 = col_double(),
                           Q146_9 = col_double(),
                           `32` = col_double(),
                           `34` = col_double(),
                           `35` = col_double(),
                           `18` = col_double(),
                           Q182_1 = col_double(),
                           Q182_2 = col_double(),
                           Q182_3 = col_double(),
                           Q182_4 = col_double(),
                           Q182_5 = col_double(),
                           Q182_6 = col_double(),
                           Q182_7 = col_double(),
                           Q106 = col_number(),
                           Q284_20 = col_double(),
                           Q284_21 = col_double(),
                           Q284_22 = col_double(),
                           Q284_23 = col_double(),
                           `98_12` = col_double(),
                           Q289_30 = col_double(),
                           Q289_29 = col_double(),
                           Q289_33 = col_double(),
                           Q289_28 = col_double(),
                           Q293_42 = col_double(),
                           Q284_16 = col_double(),
                           Q284_17 = col_double(),
                           `98_11` = col_double(),
                           Q284_18 = col_double(),
                           Q284_19 = col_double(),
                           Q98_24 = col_double(),
                           Q99_1 = col_double(),
                           Q99_2 = col_double(),
                           Q99_3 = col_double(),
                           Q99_4 = col_double(),
                           Q99_5 = col_double(),
                           Q99_6 = col_double(),
                           Q99_6_TEXT = col_character(),
                           Q99_7 = col_double(),
                           Q99_7_TEXT = col_character(),
                           Q99_8 = col_double(),
                           Q99_8_TEXT = col_character(),
                           `98_11_1` = col_double(),
                           Q289_24 = col_double(),
                           Q289_25 = col_double(),
                           Q289_26 = col_double(),
                           Q289_27 = col_double(),
                           Q289_31 = col_double(),
                           Q289_32 = col_double(),
                           Q289_34 = col_double(),
                           Q289_35 = col_double(),
                           Q289_36 = col_double(),
                           Q289_37 = col_double(),
                           Q289_38 = col_double(),
                           Q289_39 = col_double(),
                           Q289_40 = col_double(),
                           Q289_30_1 = col_double(),
                           Q289_29_1 = col_double(),
                           Q289_33_1 = col_double(),
                           Q289_28_1 = col_double(),
                           `55` = col_double(),
                           `56` = col_double(),
                           Q108 = col_double(),
                           Q184 = col_double(),
                           Q110 = col_double(),
                           Q185 = col_double(),
                           Q124 = col_double(),
                           Q128 = col_double(),
                           Q128_3_TEXT = col_logical(),
                           `58` = col_double(),
                           `59` = col_double(),
                           `30` = col_double(),
                           `30_1_TEXT` = col_character(),
                           `30_2_TEXT` = col_character(),
                           `31` = col_double(),
                           `31_1_TEXT` = col_character(),
                           `31_2_TEXT` = col_character(),
                           Q156 = col_double(),
                           `60` = col_double(),
                           `61` = col_double(),
                           Q126 = col_double(),
                           Q128_1 = col_double(),
                           Q130 = col_double(),
                           Q160 = col_double(),
                           Q189_1 = col_double(),
                           Q189_2 = col_double(),
                           Q189_3 = col_double(),
                           Q189_4 = col_double(),
                           Q189_5 = col_double(),
                           Q189_5_TEXT = col_character(),
                           Q132 = col_double(),
                           Q181 = col_double(),
                           Q116_1 = col_double(),
                           Q116_2 = col_double(),
                           Q116_3 = col_double(),
                           Q134_4 = col_double(),
                           Q134_5 = col_double(),
                           Q175_1 = col_character()
                         )) %>%
  
  # Cleaning up names using janitor::clean_names()
  
  clean_names() 
```

``` {r data_clean, cache = TRUE}

# Selecting and renaming relevant variables; assigning cleaned dataset to object
# wb_wellness

wb_wellness <- wb_wellness_raw %>%
  select(x43, x48_5, x48_3, x48_2, x48_1, x48_8, x48_11,
         x48_10, x48_9, x44_10, x45_8, x44_5, x45_9, x44_4, x44_3,
         x46_5, x48_6, x45_1, x45_2, x45_3, x45_4, x45_5, x45_6, x44_1, x46_9,
         x46_7, x46_6, x46_4, x46_2, x46_1, x45_7, x48_7, x46_8, x48_12) %>%
  rename(job_satisfaction = x43,
         fair_treatment = x48_5,
         trust_management = x48_3,
         respect = x48_2,
         caring_management = x48_1,
         helpful_management = x48_8,
         energizing_culture = x48_11,
         authentic_culture = x48_10,
         community_culture = x48_9,
         recognition = x44_10,
         predictable_schedule = x45_8,
         employee_input = x44_5,
         flexible_schedule = x45_9,
         work_autonomy = x44_4,
         clear_expectations = x44_3,
         poor_worklife_integration = x46_5,
         advancement_opportunities = x48_6,
         fair_supervisor = x45_1, 
         caring_supervisor = x45_2,
         helpful_supervisor = x45_3,
         team = x45_4,
         workfriends = x45_5,
         reliable_coworkers = x45_6,
         meaningful_work = x44_1,
         schedule_overflows = x46_9,
         mental_exhaustion = x46_7,
         physical_exhaustion = x46_6,
         long_hours = x46_4,
         stressful = x46_2,
         too_much_work = x46_1,
         rest_time = x45_7,
         fair_pay = x48_7,
         job_insecurity = x46_8,
         workplace_design = x48_12
         ) %>%
  
  # Dropping incomplete responses
  
  drop_na()

```

```{r tidy_split}

# Splitting my data into training and testing sets using functions from the
# tidymodels metapackages

set.seed(10)
wb_split <- initial_split(wb_wellness, prop = 0.80)
wb_train <- training(wb_split)
wb_test  <- testing(wb_split)
wb_folds <- vfold_cv(wb_train, v = 10)
```


```{r recipe}

# Building a recipe for data processing

sat_rec <- recipe(
  
   # Telling the recipe() what my model is going to be (using a formula here)
   # and what my training data is.
  
  job_satisfaction ~ .,
  data = wb_train) %>%

  #  Removing any numeric variables that have zero variance
  
  step_zv(all_numeric(), -all_outcomes()) %>%
  
  # Normalizing (centering and scaling) the numeric variables. This is important
  # for lasso regularization.
  
  step_normalize(all_numeric(), -all_outcomes())

# Creating a recipe whose step objects have been updated with the required
# pre-processing parameters

sat_prep <- sat_rec %>%
  prep()

# Specifying and then fitting my model

# Here I set up one model specification for lasso regression; I picked a value
# for penalty (sort of randomly) and I set mixture = 1 for lasso.

lasso_spec <- linear_reg(penalty = 0.1, mixture = 1) %>%
  set_engine("glmnet")

# Adding a recipe to my workflow

wf <- workflow() %>%
  add_recipe(sat_rec)

# Adding model to workflow and fitting workflow with training data

lasso_fit <- wf %>%
  add_model(lasso_spec) %>%
  fit(data = wb_train)

# Pulling the fit object so that I can tidy() it

lasso_fit %>%
  pull_workflow_fit() %>%
  tidy()
```


```{r tuning}

#  Determining right regularization parameter "penalty" by using resampling and
#  tuning the model.
 
doParallel::registerDoParallel()
set.seed(10)

# Building a set of bootstraps resamples

wb_boot <- bootstraps(wb_train)

# Setting penalty = tune() instead of to a single value.

tune_spec <- linear_reg(penalty = tune(), mixture = 1) %>%
  set_engine("glmnet")

# Using penalty() function to set up an appropriate grid for this kind of
# regularization model.

lambda_grid <- grid_regular(penalty(), levels = 50)

# Tuning grid using workflow object
lasso_grid <- tune_grid(
  wf %>% add_model(tune_spec),
  resamples = wb_boot,
  grid = lambda_grid)
```

```{r metrics}

# Collecting results after tuning grid and visualizing performance with the
# regularization parameter.

lasso_grid %>%
  collect_metrics() %>%
  ggplot(aes(penalty, mean, color = .metric)) +
  geom_errorbar(aes(ymin = mean - std_err,
                    ymax = mean + std_err),
                alpha = 0.5) +
  geom_line(size = 1.5) +
  facet_wrap(~.metric, scales = "free", nrow = 2) +
  scale_x_log10() +
  theme(legend.position = "none")
```

```{r final_reg_parameter}

# Choosing final regularization parameter based on lowest RMSE

lowest_rmse <- lasso_grid %>%
  select_best("rmse")

# Updating workflow with this value

final_lasso <- finalize_workflow(wf %>% 
                                   add_model(tune_spec),
                                 lowest_rmse
                                 )
```

```{r final_wfl}

# Plotting importance of each variable based on fitting model to training data

final_lasso %>%
  
  # Fitting model to training data
  
  fit(wb_train) %>%
  pull_workflow_fit() %>%
  
  # Running vi() (variable importance) function on fitted model, setting lambda
  # to the penalty in the model with the lowest RMSE
  
  vi(lambda = lowest_rmse$penalty) %>%
  
  # Mutating Importance column to absolute values; mutating Variable column so
  # that it is ordered by Importance
  
  mutate(Importance = abs(Importance),
         Variable = fct_reorder(Variable, Importance)) %>%
  ggplot(aes(x = Importance, y = Variable, fill = Sign)) +
  geom_col() +
  scale_x_continuous(expand = c(0, 0.01)) +
  labs(y = NULL) +
  theme_linedraw()

```

```{r last_fit}

# Finally, I am returning to my testing data

# The tune package has a function last_fit(); now that I have tuned and
# finalized my workflow/model, I want to fit it one last time on my training
# data and evaluate it on my testing data. I only have to pass this function my
# finalized model/workflow and my split data.

last_fit(final_lasso, wb_split) %>%
  collect_metrics()

```
```{r final_model}

# Final model fit to entire data set

sat_fit <- final_lasso %>%
  fit(wb_wellness)

sat_fit %>%
  tidy()
```

```{r save_model}

# Saving model as a .rds file

write_rds(sat_fit, "sat_fit.rds")

```


```{r importance_scores}

# Saving variable importance scores tibble as a .rds file

sat_vi <- sat_fit %>%
  pull_workflow_fit() %>%
  vi(lambda = lowest_rmse$penalty) 

write_rds(sat_vi, "sat_vi.rds")
```



```{r final_plot}

# Plotting importance of each variable based on fitting model to entire dataset

sat_fit %>%
  pull_workflow_fit() %>%
  vi(lambda = lowest_rmse$penalty) %>%
  mutate(Importance = abs(Importance),
         Variable = fct_reorder(Variable, Importance)) %>%
  ggplot(aes(x = Importance, y = Variable, fill = Sign)) +
  geom_col() +
  scale_x_continuous(expand = c(0, 0.01)) +
  labs(y = NULL,
       title = "Variable Importance Scores", 
       subtitle = "Sense of meaning in work and feeling recognized are the most\nimportant predictors of overall job satisfaction")+
  theme_light()

# The most important predictors of WBG employees' overall job satisfaction are
# meaningful_work, recognition, fair_pay, team, job_insecurity,
# helpful_management, and work_autonomy.
```

# Code

```{r print-code, ref.label=knitr::all_labels(), echo = TRUE, eval=FALSE} 

# This command will print out my code.

```
